### PR TITLE
Fix filename highlight in part 5

### PR DESCRIPTION
**Pull request by rtjfarrimond**
Filename highlight in part 5 indicated to uncomment code in `toymir.py`. Changed to `toymir/freq.py`.

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks for doing this.  Note however that the html pages are auto-generated from jekyll, so any corrections should be applied to the source files and not the output html.

**Comment by rtjfarrimond** [comment]
Cool, will take another look when I get a moment 👍

**Comment by rtjfarrimond** [comment]
Hey Brian, markdown now updated :)

**Comment by bmcfee** [comment]
LGTM, thanks!

**Pull request merged**
